### ISSUE TITLE
geckolib incompatibility?!?

### ISSUE THREAD

**Issue by DadoIrie** [Team-Abode/scribe-WIP#1]
not sure, but scribe is being mentioned in the logs on every entity that is animated with geckolib
a literal error invasion - starting here: https://mclo.gs/295lJBM#L2040

it did not crash, but obviously the resource load failed and upon attempting to join the server the client crashes

I have Guarding! which uses scribe, but I assume that most likely this is a scribe issue

**Comment by ExDrill** [comment]
Thanks for reporting, this was fixed in the latest version of Scribe, which is currently directly integrated into Guarding!
